### ISSUE TITLE
Support for Jetpack Compose 1.x.x

### ISSUE THREAD

**Issue by sergio-sastre** [pedrovgs/Shot#250]
### Expected behaviour
Successfully run a snapshot test for a Compose View using Jetpack Compose 1.0.1

### Actual behaviour
I get the following error:
```
> Task :app:connectedDebugAndroidTest
Starting 4 tests on Pixel_4_API_23_Marshmallow(AVD) - 6.0

com.example.road.to.effective.snapshot.testing.parameterized.ComposeParameterized > helloTest[Pixel_4_API_23_Marshmallow(AVD) - 6.0] FAILED 
        java.lang.NoClassDefFoundError: androidx.compose.ui.test.android.WindowCapture_androidKt$captureRegionToImage$onCopyFinished$1
        at androidx.compose.ui.test.android.WindowCapture_androidKt.captureRegionToImage(WindowCapture.android.kt:97)

> Task :app:connectedDebugAndroidTest FAILED
```

### Steps to reproduce
configure Jetpack Compose 1.0.1 and write a snapshot test for it, using `ComposeRule` and `compareScreenshot(composeRule.onRoot())`, `compareScreenshot(composeRule.onRoot().captureToImage())` or `compareScreenshot(composeRule.onRoot().captureToImage().asAndroidBitmap())`

### Version of the library
Shot 5.11.2

Remarks:
I've taken a look and shot 5.11.2 is configured for Jetpack Compose Beta 3. Its Gradle configuration and methods differ a lot from those for Jetpack Compose 1.0.0

**Comment by pedrovgs** [comment]
Thanks for reporting @sergio-sastre I tested the latest shot version with Compose 1.x and it was working as expected. Are you sure the issue is related to compose? Anyway, right now I'm working on a different project and I don't know if I'll have time to fix this soon. Could you please send a PR with the fix. If you find any blocker, I could personally help you 😃 Thank you in advance!

**Comment by boguszpawlowski** [comment]
@sergio-sastre Can you share more of your setup for tests? We have been able to successfully run screenshot tests with compose 1.0.1 on external project.

**Comment by sergio-sastre** [comment]
Hi there! 
Sorry for my late reply! Let me check it out again in the evening, but I am afraid you are right, it should be something on my side

**Comment by sergio-sastre** [comment]
Yep, was something misconfigured on my side, I will close this :)

**Comment by jakob-grabner** [comment]
@sergio-sastre I  have the same issue, could you please share how you could solve the issue?

**Comment by sergio-sastre** [comment]
Hi @jakob-grabner ! I actually remove composable and after a while I tried it out again, I believe with a 1.0.1 beta version instead, and it worked.

Could you share your setup to facilitate debugging?
