### ISSUE TITLE
"unknown" test case and test name

### ISSUE THREAD

**Issue by davidbilik** [pedrovgs/Shot#252]
### Expected behaviour
When I run a test on Pixel 4 with Android 12 Beta 4 or on Pixel 5 with Android 11, screenshots are named "$testClassName_$testName.png"

### Actual behaviour
When I run a test on Pixel 4 with Android 12 Beta 4 or on Pixel 5 with Android 11, screenshots are named "unknown_unknown.png"

### Steps to reproduce
- Create a new Android Studio project
- Integrate a library
- Write a simple test
```kotlin
@RunWith(AndroidJUnit4::class)
class ExampleInstrumentedTest : ScreenshotTest {

    @Test
    fun useAppContext() {
        val scenario = launchActivity<MainActivity>()
        scenario.waitForActivity()
        scenario.onActivity {
            compareScreenshot(it)
        }
    }
}
```

- ### Version of the library
`5.11.2`

### Notes

My humble guess is that it's tied to facebooks `TestNameDetector` which is unable to extract those info from the Stacktrace. I've tried the commands mentioned [here](https://github.com/Karumi/Shot#using-shot-on-api-28) but no luck. I also tried [this](https://github.com/ChickenHook/RestrictionBypass) library for bypassing restrictions and nada :(

**Comment by pedrovgs** [comment]
Hey @davidbilik are you sure the library is not working. If you run the compareScreenshot from the test thread it should be working. Did you try writing your test like this?

```kotlin
 @Test
    fun useAppContext() {
        val scenario = launchActivity<MainActivity>()
        compareScreenshot(scenario.waitForActivity())
    }
```

**Comment by pedrovgs** [comment]
Anyway I think this one is duplicated by https://github.com/pedrovgs/Shot/issues/135

**Comment by pedrovgs** [comment]
Closing because it is duplicated.
