### ISSUE TITLE
Failing to record screenshot should fail test with a exception instead of posting a silent error report

### ISSUE THREAD

**Issue by crysxd** [pedrovgs/Shot#253]
We recently set up screenshot tests for our app, generating roughly 1600 screenshots. Locally, everything worked well, but on our CI system tests did not fail although the recorded screenshots were clearly wrong. We found out that only ~600 screenshots are generated on the CI (so over 1000 were missing).

After plenty of debugging we found the issue to be a missing `adb shell settings put global hidden_api_policy  1`. 

### Expected behaviour
When the framework fails to record a screenshot, the test should fail and not swallow the error and continue

### Actual behaviour
Error is logged to Logcat and tests continue and succeed

```kotlin
try {
    Screenshot
        .snap(view)
        .setIncludeAccessibilityInfo(false)
        .setName(snapshotName)
        .record()
} catch (t: Throwable) {
    Log.e("Shot", "Exception captured while taking screenshot for snapshot with name $snapshotName", t) // this is logged
   // Should be: throw IllegalStateException("Exception occurred while taking screenshot for snapshot with name $snapshotName", t)
}
```

### Steps to reproduce
Test on Android 11 without `adb shell settings put global hidden_api_policy  1`. I'm not sure why some tests were able to record screenshots and others were not

### Version of the library
5.11.2

**Comment by pedrovgs** [comment]
Hi @crysxd thanks for reporting. You are absolutely right, we should throw an exception when this happens. Looks like you've found the perfect change in our project codebase, could you please send the fix for this issue?

**Comment by pedrovgs** [comment]
Thanks for your contribution @nrotonda 😃 the next will include this fix.
