### ISSUE TITLE
Question: Possibility to test dark mode?

### ISSUE THREAD

**Issue by Windisch94** [pedrovgs/Shot#260]
Is it possible to test screenshots in Darkmode also? 
For example if I have following Preview:

> @Preview(name = "Light mode")
@Preview(
    uiMode = UI_MODE_NIGHT_YES,
    name = "Dark mode"
)
@Composable
fun TestPreview() {
    Text("dummy text")
}

This results only in one screenshot in light mode. Is it possible to set a setting or something to capture a screenshot in the dark mode?

**Comment by sergio-sastre** [comment]
I am afraid it does not work because @Preview is just that, a preview, and it does not affect the layout at all.

However, it is definitely possible. The easiest way to do it is with Parameterized tests.

If you are using Jetpack Compose, first of all you need to define the darkMode and lightMode colors in a file, something like this

```kotlin
val lightThemeColors = lightColors(
    primary = Color(0xFF855446),
    primaryVariant = Color(0xFF9C684B),
    secondary = Color(0xFF03DAC5),
    secondaryVariant = Color(0xFF0AC9F0),
    background = Color.White,
    surface = Color.White,
    error = Color(0xFFB00020),
    onPrimary = Color.White,
    onSecondary = Color.White,
    onBackground = Color.Black,
    onSurface = Color.Black,
    onError = Color.White
)

val darkThemeColors = darkColors(
    primary = Color(0xFF1F1F1F),
    primaryVariant = Color(0xFF3E2723),
    secondary = Color(0xFF03DAC5),
    background = Color(0xFF121212),
    surface = Color.Black,
    error = Color(0xFFCF6679),
    onPrimary = Color.White,
    onSecondary = Color.White,
    onBackground = Color.White,
    onSurface = Color.White,
    onError = Color.Black
)

@SuppressWarnings
@Composable
fun AppTheme(
    content: @Composable () -> Unit
) {
    val colors = if (isSystemInDarkTheme()) {
        darkThemeColors
    } else {
        lightThemeColors
    }

    MaterialTheme(
        colors = colors,
        content = content
    )
}
```

And then write a Parameterized test, which will take the theme as parameter. Here an example for a snapshot test in light and dark mode:

```kotlin
@RunWith(Parameterized::class)
class ExperimentalTest(private val testItem: TestItem) : ScreenshotTest {

   data class TestItem(val theme: Colors, val testName: String)

   @get:Rule
   val composeTestRule = createEmptyComposeRule()

    companion object {
        @JvmStatic
        @Parameterized.Parameters
        fun data(): Array<TestItem> =
            arrayOf( //every item in the array is a test!
                TestItem(darkThemeColors, "DARK"),
                TestItem(lightThemeColors, "LIGHT")
            )
    }

    @Test
    fun snapComposable() {
        ActivityScenario.launch(MyActivity.class).onActivity {
            it.setContent {
                textPreview()
            }
        }

        compareScreenshot(composeTestRule, name = testItem.testName)
    }
}
```

Something similar to this should work ;)

**Comment by sergio-sastre** [comment]
There is also an interesting article on how to do it by @fabiocarballo:
https://www.fabiocarballo.dev/blog/multi_theme_screenshots_tests_in_compose/

**Comment by pedrovgs** [comment]
As soon as you are able to render a component using different config values you will be able to take the screenshot, so yeap, you can do it 😃 I hope this is the answer to your question. Please, feel free to reopen it if you have any other doubt. Sorry for the late response and thank you all @sergio-sastre, and @CedrickFlocon for your answers.
