### ISSUE TITLE
Problem running in CI

### ISSUE THREAD

**Issue by leandroBorgesFerreira** [pedrovgs/Shot#261]
When I run:
```
./gradlew my_project:demoDebugExecuteScreenshotTests
```

In this CI, I always get: `We couldn't find any screenshot. Did you configure Shot properly and added your tests to your project?` Although the tests work fine locally and the screenshots are available in the CI aswell. 
### Expected behaviour
The tests run with no problems in the CI

### Actual behaviour
 I always get: `We couldn't find any screenshot. Did you configure Shot properly and added your tests to your project?`

### Steps to reproduce
I'm running this PR: https://github.com/GetStream/stream-chat-android/pull/2499. and one of the actions presents this error.

### Version of the library
0.8.0

Is this error known? Is there any workaround? Or perhaps is this an error on my end?

**Comment by pedrovgs** [comment]
Hey, sorry for the late response. Looking at the error message and the current state of the repository the issue seems to be fixed. Please, let me know if you need more help.
