### ISSUE TITLE
We couldn't find any screenshot

### ISSUE THREAD

**Issue by codeteo** [pedrovgs/Shot#280]
### Expected behaviour
Generate a screenshot for the fragment I want to screenshot test when running `./gradlew executeScreenshotTests -Precord`

### Actual behaviour
When using an older version of `Shot` library (for example `5.5.0`) I get the following response : 

```
> Task :app:debugExecuteScreenshotTests
💾  Saving screenshots.
🤔 We couldn't find any screenshot. Did you configure Shot properly and added your tests to your project? https://github.com/Karumi/Shot/#getting-started

```

While when I use the latest version (that is `5.12.1`) what I get is : 

```
com.parallel.shots.FragmentScreenshotTest > theActivityIsShownProperly[3.2_HVGA_slider_ADP1_API_28(AVD) - 9] FAILED 
        java.lang.IllegalStateException: Fragment FirstFragment{1aedfba} (1eaa1af4-0307-4b25-bf51-ec2dc838aa9a) did not return a View from onCreateView() or this was called before onCreateView().
        at androidx.fragment.app.Fragment.requireView(Fragment.java:2008)
Tests on 3.2_HVGA_slider_ADP1_API_28(AVD) - 9 failed: There was 1 failure(s).


```

### Steps to reproduce
Download the sample project from [here](https://github.com/codeteo/ParallelScreenshotTests)

### Version of the library
`5.5.0` and `5.12.1`

I've also downloaded [KataScreenshotKotlin](https://github.com/Karumi/KataScreenshotKotlin) and when ran  `./gradlew executeScreenshotTests -Precord` works as expected (generates the screenshots) so I guess its not a problem with the emulator.
Do you mind checking the sample project I uploaded and tell me whats wrong ? Most probably I have configured something wrong although I read the getting start guide from the README many times. 
Thanks a lot for your time!

Edit: Dont know if it matters but I'm using `Android Studio Chipmunk | 2021.2.1 Canary 7`

**Comment by codeteo** [comment]
Oh my bad just found out [this comment here ](https://github.com/pedrovgs/Shot/issues/221#issuecomment-824191381) which helped resolve my issue. I just had to create a folder `project/screenshots/flavour/debug/screenshots-default`

**Comment by codeteo** [comment]
Sorry for re-opening the issue but it worked only the first time I tried it, for every subsequent run I keep getting the same error : 

```
com.parallel.shots.FragmentScreenshotTest > theActivityIsShownProperly[3.2_HVGA_slider_ADP1_API_28(AVD) - 9] FAILED 
        java.lang.IllegalStateException: Fragment FirstFragment{1aedfba} (c10036c7-9088-4060-ae7e-7068e1299695) did not return a View from onCreateView() or this was called before onCreateView().
        at androidx.fragment.app.Fragment.requireView(Fragment.java:2008)

```

**Comment by pedrovgs** [comment]
Hey @codeteo that issue you report seems not to be related with the library but with your fragments' configuration. Could you please remove this line [here](https://github.com/codeteo/ParallelScreenshotTests/blob/main/app/src/androidTest/java/com/parallel/shots/FragmentScreenshotTest.kt#L16) and execute your test again? If it fails, the issue is not related to shot but the fragments initialized.
