### ISSUE TITLE
Tolerance value warning documentation is not correct

### ISSUE THREAD

**Issue by adrinieto** [pedrovgs/Shot#282]
In the tolerance sections states that:

> If you configure tolerance = 1 it means the tolerance threshold will be 100% and all your tests will pass even if they should fail...so be careful when configuring this param.

Where it says `tolerance = 1` should be `tolerance = 100`. 

We have failing tests that need a value higher than 1 to pass and in the logs for the passing tests it shows "1.0%"

> ⚠️   Shot warning: There are some pixels changed in the screenshot named com.jobandtalent.android.candidates.opportunities.process.detail.process.ProcessNextStepsFragmentScreenshotTest_shouldShowNextStepsWithAllDoneState, but we consider the comparison correct because **tolerance is configured to 1.0 %** and the percentage of different pixels is 0.19463734567901234 %

Also, in the `shot-consumer-compose` [build.gradle](https://github.com/pedrovgs/Shot/blob/6288ac3a23b141c02911ec1ec6273ea18d365dcd/shot-consumer-compose/app/build.gradle#L67) is set to `1.1`

**Comment by pedrovgs** [comment]
I think you are right @adrinieto

I'm checking the code where tolerance is computed and it shows:

```scala
 val percentageOfDifferentPixels = differentPixels.length.toDouble / oldScreenshotPixels.length.toDouble
val percentageOutOf100        = percentageOfDifferentPixels * 100.0
val imagesAreDifferent        = percentageOutOf100 >= tolerance
```

If ``differentPixels.length.toDouble`` is 7 and ``oldScreenshotPixels.length.toDouble`` is 100. ``percentageOutOf100`` will be 7. Representing 7% of the pixel values changed. As the value read from the config is not modified at all. If the shot config is like this:

```
shot {
   tolerance = 100
```

This means 100% of the tests are allowed to be different. I know you've sent a PR changing this combined with another huge change, but I'm going to send a PR changing only our docs. Thanks!
