### ISSUE TITLE
One set of screenshots recorded when running multiple emulators

### ISSUE THREAD

**Issue by karsie** [pedrovgs/Shot#284]
When running multiple emulators to record screenshots on different sizes and API versions, previously for all devices the screenshots were downloaded (when unique filenames were used). Since 5.12.2 only the screenshots of the last device (highest emulator id) are successfully recorded.

### Expected behaviour
All screenshots of all emulators to be recorded

### Actual behaviour
Only screenshots of "last" emulator is recorded

### Steps to reproduce
start emulator-5554 api30
start emulator-5556 api28
start emulator-5558 api26

./gradlew executeScreenshotTests -Precord

### Version of the library
AGP 7.0.3
Shot 5.12.2 (worked perfectly on 5.12.1, also broken on 5.13.0 with or without facebook 0.14.0)
Facebook 0.13.0

**Comment by TomSenier** [comment]
We have noticed the exact same issue when we upgraded from 5.11.2 to 5.13.0
