### ISSUE TITLE
Screenshot tests take huge time to run

### ISSUE THREAD

**Issue by mittalshivansh** [pedrovgs/Shot#302]
I feel the current approach for composing screenshot testing is not scalable as it takes a huge time to run a single test. Currently, for each screenshot test, a new activity is instantiated. Can we do something to share single instance of activity to optimize the time.

**Comment by pedrovgs** [comment]
It all depends on the U library you are using @mittalshivansh. If you are using old android views, you'll be able to inflate different views and take as many screenshots as you want with only 1 activity instantiated only 1 time. However, the compose testing tools don't provide this capability. At least it didn't provide it last time I checked. I hope this is the answer to your question.
