### ISSUE TITLE
 ImageLoader must be init

### ISSUE THREAD

**Issue by dbayon** [pedrovgs/Shot#310]
### Expected behaviour
Record snapshots of compose component

### Actual behaviour
while recording snapshots the following error appears in console:

com.playtomic.AcademyDetailSnapshotsMviTests > testAcademyDetailView[Pixel_4_API_29(AVD) - 10] FAILED 
        java.lang.IllegalStateException: ImageLoader must be init with configuration before using
        at com.nostra13.universalimageloader.core.ImageLoader.checkConfiguration(ImageLoader.java:613)

### Steps to reproduce
Execute shot task with -Precord

### Version of the library
5.14.1

**Comment by pedrovgs** [comment]
Hey @dbayon can you check if this is reproducible with a previous version? Can you try with 5.13.0 or 5.12.2?

P.S: I play padel @dbayon , but my playtomic level is not updated xD
