### ISSUE TITLE
With ANDROIDX_TEST_ORCHESTRATOR only one screenshot is retrieved

### ISSUE THREAD

**Issue by tobiasKaminsky** [pedrovgs/Shot#78]
### Expected behaviour
- record/verify all screenshots

### Actual behaviour
- only one (latest) screenshot is retrieved

### Steps to reproduce
- have multiple screenshot tests
- execute it

### Version of the library
3.1.0

For a quick test project, please see: https://github.com/tobiasKaminsky/KarumiTest

Commenting this
https://github.com/tobiasKaminsky/KarumiTest/blob/adea1c075876454da439315eeaf9c9960c563b23/app/build.gradle#L21
will retrieve two screenshots, else only one.

Gradle task: ./gradlew executeScreenshotTests -Precord

**Comment by tobiasKaminsky** [comment]
Related to #64, but created a new one, as the other one is closed.

**Comment by Serchinastico** [comment]
Thanks for reporting and the demo project, we will be taking a look in the following weeks!

**Comment by pedrovgs** [comment]
Thanks for creating the demo project @tobiasKaminsky I've tested the repository and the issue seems to be related to the Facebook library we use to take the screenshots. As I plan to update the version we use but this is a HUGE change I'm leaving this issue here as is until we update the core library and we release a new version.

**Comment by ursimon** [comment]
Hi, is there a way to test `3.1.1-SNAPSHOT` version ?

**Comment by pedrovgs** [comment]
Not for now @ursimon . I'm afraid I didn't release any snapshot for now. But you can use the latest stable version if you want.

**Comment by ursimon** [comment]
Yeah, but I have the same issue as described above, so I thought I would give a go updated version as update of Facebook lib has been merged...

**Comment by pedrovgs** [comment]
I'm afraid we will have to wait :( I'm also wondering why you want to use the ANDROIDX orchestrator 🤔Could you tell us why @ursimon @tobiasKaminsky ?

**Comment by tobiasKaminsky** [comment]
It is said that this makes tests more robust as they are run isolated/sandboxed and thus leftovers from previous tests do not (or less) affect the following tests.

**Comment by pedrovgs** [comment]
Ok, I'll check if this works after the internal Facebook library update. If it's not working I'll check if we can do something to fix it from our side.

**Comment by reisfernanda** [comment]
I'm facing the same issue, do you have any update on this?

**Comment by pedrovgs** [comment]
Hi @reisfernanda I've been working on different issues and I had no time to fix this. However, we are always open to new contributors in case you can find some time to review it.

**Comment by reisfernanda** [comment]
Hi @pedrovgs thanks for the quick reply.
In the meanwhile, I'm disabling Android Test Orchestrator only when recording the screenshots.

**Comment by VysotskiVadim** [comment]
Seems it's an issue in facebook library, which hasn't been fixed yet.
If somebody want to help community and implement Android Test Orchestrator support, you can find all the details here https://github.com/facebook/screenshot-tests-for-android/issues/173

**Comment by pedrovgs** [comment]
I've been reviewing @VysotskiVadim and right now there is no way we can get it working without Facebook's fix 😢  I'm afraid I'm closing this issue as there is nothing we can do to fix it. Thank you all for your comments and suggestions.

**Comment by ddudek** [comment]
👋  just to let you know - facebook screeshot lib just added support for orchestrator in 0.14.0

**Comment by pedrovgs** [comment]
Reopening this issue just to see if we can provide proper support for the test orchestrator now that facebook seems to be supporting it.

**Comment by iadcialim** [comment]
Btw. is there a work around on clearing cache without using orchestrator so the it can create screenshots on all tests?

**Comment by mariuszmarzec** [comment]
@pedrovgs I have started investigating it. I created a branch in my forked repository.
What i have managed?
- Updated facebook lib to newest version
- Preserving screenshots and pulling them for regular screenshots

Code is ugly now and far from final solution. It remains a lot work like: broken clearing dirs, assembling images, but i have a plan to work on it slowly.

Suggestions, feedback, comments and ideas welcome

https://github.com/pedrovgs/Shot/compare/master...mariuszmarzec:feature/ISSUE-78_test_orchestrator_support?expand=1

**Comment by mariuszmarzec** [comment]
Finished implementation in connected PR. If anybody could check code and test orchestration support in your project for more feedback would be great. @pedrovgs In my opinion is ready to merge, but if anything could be done better, will do it. 
Tested on API 28

**Comment by pedrovgs** [comment]
Releasing a new version today.
